id: shulkerbox

require:
  - bolt_expressions
  - bolt_expressions.contrib.commands
  - bolt
  # - plugins.fancy_macros
  - mecha.contrib.nesting
  - bolt.contrib.defer
  # - mecha.contrib.bake_macros
  - plugins.custom_load
  - plugins.component_caching

pipeline:
  - mecha

data_pack:
  load: [vendor/persist]

  filter:
    block:
      - namespace: "minecraft"
        path: "recipes/*"
      - namespace: "minecraft"
        path: "advancements/*"
      - namespace: "minecraft"
        path: "loot_tables/*"

output: dist

meta:
  generate_namespace: "server"

  bolt:
    entrypoint: ["*"]
    prelude: ["server:prelude"]

  bolt_expressions:
    temp_objective: "temp"
    const_objective: "const"
    temp_storage: "bolt:temp"
    init_path: "load/init_objectives"
