id: shulkerbox

require:
  # it needs to go first so that exit phase happens last
  - plugins.upload

  - bolt_expressions
  - bolt_expressions.contrib.commands
  - bolt
  - mecha.contrib.nesting
  - bolt.contrib.defer
  - plugins.component_caching

  # needs to go last
  - plugins.custom_load

pipeline:
  - mecha

data_pack:
  load: [vendor/persist]

  filter:
    block:
      - namespace: "minecraft"
        path: "recipes/*"
      - namespace: "minecraft"
        path: "advancements/*"
      - namespace: "minecraft"
        path: "loot_tables/*"

output: dist

meta:
  deploy: false
  generate_namespace: "server"

  bolt:
    entrypoint: "*"
    prelude: ["server:prelude"]

  bolt_expressions:
    temp_objective: "temp"
    const_objective: "const"
    temp_storage: "bolt:temp"
    init_path: "core/load/init_objectives"
